<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net462</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\src\Karambolo.Public.snk</AssemblyOriginatorKeyFile>
    <DefaultItemExcludes>Fixtures.RegExp\Generator\**;$(DefaultItemExcludes)</DefaultItemExcludes>
    <AnalysisLevel>None</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System.ComponentModel.Composition" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="UnicodeInformation.Preview" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Acornima.Extras\Acornima.Extras.csproj" />
  </ItemGroup>

</Project>
