using System;

namespace Acornima;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
internal sealed class AutoGeneratedAstVisitorAttribute : Attribute
{
    public Type? VisitorType { get; set; }
    public string? TargetVisitorFieldName { get; set; }
    public string? BaseVisitorFieldName { get; set; }
}
