//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acornima {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtrasExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtrasExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acornima.Properties.ExtrasExceptionMessages", typeof(ExtrasExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assignment operator..
        /// </summary>
        internal static string InvalidAssignmentOperator {
            get {
                return ResourceManager.GetString("InvalidAssignmentOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid binary operator..
        /// </summary>
        internal static string InvalidBinaryOperator {
            get {
                return ResourceManager.GetString("InvalidBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent must be null or white-space..
        /// </summary>
        internal static string InvalidIndent {
            get {
                return ResourceManager.GetString("InvalidIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token type..
        /// </summary>
        internal static string InvalidTokenType {
            get {
                return ResourceManager.GetString("InvalidTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unary operator..
        /// </summary>
        internal static string InvalidUnaryOperator {
            get {
                return ResourceManager.GetString("InvalidUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member must be within an object..
        /// </summary>
        internal static string JsonMemberOutsideObject {
            get {
                return ResourceManager.GetString("JsonMemberOutsideObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON text must start with an object or an array..
        /// </summary>
        internal static string JsonTextMustStartWithObjectOrArray {
            get {
                return ResourceManager.GetString("JsonTextMustStartWithObjectOrArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for member &apos;{0}&apos;..
        /// </summary>
        internal static string MissingJsonMemberValue {
            get {
                return ResourceManager.GetString("MissingJsonMemberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unterminated JSON structure..
        /// </summary>
        internal static string NoUnterminatedJsonStructure {
            get {
                return ResourceManager.GetString("NoUnterminatedJsonStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not defined for nodes of type {0}..
        /// </summary>
        internal static string OperationNotDefinedForNodeType {
            get {
                return ResourceManager.GetString("OperationNotDefinedForNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator precedence for expression of type {0} is not defined..
        /// </summary>
        internal static string OperatorPrecedenceNotDefined {
            get {
                return ResourceManager.GetString("OperatorPrecedenceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON object member name is undefined..
        /// </summary>
        internal static string UndefinedJsonMemberName {
            get {
                return ResourceManager.GetString("UndefinedJsonMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has an associated node property but its value is a node list..
        /// </summary>
        internal static string WriteContextHasAssociatedNodeListProperty {
            get {
                return ResourceManager.GetString("WriteContextHasAssociatedNodeListProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has an associated node property but its value is not a node list..
        /// </summary>
        internal static string WriteContextHasAssociatedSingleNodeProperty {
            get {
                return ResourceManager.GetString("WriteContextHasAssociatedSingleNodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has no associated node property..
        /// </summary>
        internal static string WriteContextHasNoAssociatedProperty {
            get {
                return ResourceManager.GetString("WriteContextHasNoAssociatedProperty", resourceCulture);
            }
        }
    }
}
