//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acornima.Jsx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsxSyntaxErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsxSyntaxErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acornima.Properties.JsxSyntaxErrorMessages", typeof(JsxSyntaxErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSX attributes must only be assigned a non-empty expression.
        /// </summary>
        internal static string JsxAttributeIsEmpty {
            get {
                return ResourceManager.GetString("JsxAttributeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected corresponding JSX closing tag for &lt;{0}&gt;.
        /// </summary>
        internal static string JsxMissingClosingTagElement {
            get {
                return ResourceManager.GetString("JsxMissingClosingTagElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSX value should be either an expression or a quoted JSX text.
        /// </summary>
        internal static string JsxUnsupportedValue {
            get {
                return ResourceManager.GetString("JsxUnsupportedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated JSX contents.
        /// </summary>
        internal static string JsxUnterminatedContent {
            get {
                return ResourceManager.GetString("JsxUnterminatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacent JSX elements must be wrapped in an enclosing tag.
        /// </summary>
        internal static string JsxUnwrappedAdjacentElements {
            get {
                return ResourceManager.GetString("JsxUnwrappedAdjacentElements", resourceCulture);
            }
        }
    }
}
