//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acornima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParseErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParseErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acornima.Properties.ParseErrorMessages", typeof(ParseErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0} from the adapted pattern ({1}) and options ({2}).
        /// </summary>
        internal static string RegexCreationFailed {
            get {
                return ResourceManager.GetString("RegexCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert regular expression to an equivalent {0}: /{1}/{2}: {3}.
        /// </summary>
        internal static string RegExpConversionFailed {
            get {
                return ResourceManager.GetString("RegExpConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconvertible forward reference.
        /// </summary>
        internal static string RegExpInconvertibleForwardReference {
            get {
                return ResourceManager.GetString("RegExpInconvertibleForwardReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconvertible named forward reference.
        /// </summary>
        internal static string RegExpInconvertibleNamedForwardReference {
            get {
                return ResourceManager.GetString("RegExpInconvertibleNamedForwardReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconvertible {} quantifier.
        /// </summary>
        internal static string RegExpInconvertibleRangeQuantifier {
            get {
                return ResourceManager.GetString("RegExpInconvertibleRangeQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconvertible Unicode property escape.
        /// </summary>
        internal static string RegExpInconvertibleUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("RegExpInconvertibleUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode sets mode (flag v) is not supported currently.
        /// </summary>
        internal static string RegExpUnicodeSetsModeNotSupported {
            get {
                return ResourceManager.GetString("RegExpUnicodeSetsModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map group name &apos;{0}&apos; to a unique group name in the adapted regex.
        /// </summary>
        internal static string RegExpUnmappableGroupName {
            get {
                return ResourceManager.GetString("RegExpUnmappableGroupName", resourceCulture);
            }
        }
    }
}
