//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acornima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyntaxErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyntaxErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acornima.Properties.SyntaxErrorMessages", typeof(SyntaxErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression flags.
        /// </summary>
        internal static string InvalidRegExpFlags {
            get {
                return ResourceManager.GetString("InvalidRegExpFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Duplicate capture group name.
        /// </summary>
        internal static string RegExpDuplicateCaptureGroupName {
            get {
                return ResourceManager.GetString("RegExpDuplicateCaptureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Incomplete quantifier.
        /// </summary>
        internal static string RegExpIncompleteQuantifier {
            get {
                return ResourceManager.GetString("RegExpIncompleteQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid capture group name.
        /// </summary>
        internal static string RegExpInvalidCaptureGroupName {
            get {
                return ResourceManager.GetString("RegExpInvalidCaptureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid character class.
        /// </summary>
        internal static string RegExpInvalidCharacterClass {
            get {
                return ResourceManager.GetString("RegExpInvalidCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid class escape.
        /// </summary>
        internal static string RegExpInvalidClassEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidClassEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid decimal escape.
        /// </summary>
        internal static string RegExpInvalidDecimalEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidDecimalEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid escape.
        /// </summary>
        internal static string RegExpInvalidEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid group.
        /// </summary>
        internal static string RegExpInvalidGroup {
            get {
                return ResourceManager.GetString("RegExpInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid named capture referenced.
        /// </summary>
        internal static string RegExpInvalidNamedCaptureReferenced {
            get {
                return ResourceManager.GetString("RegExpInvalidNamedCaptureReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid named reference.
        /// </summary>
        internal static string RegExpInvalidNamedReference {
            get {
                return ResourceManager.GetString("RegExpInvalidNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid property name.
        /// </summary>
        internal static string RegExpInvalidPropertyName {
            get {
                return ResourceManager.GetString("RegExpInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid property name in character class.
        /// </summary>
        internal static string RegExpInvalidPropertyNameInCharacterClass {
            get {
                return ResourceManager.GetString("RegExpInvalidPropertyNameInCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid quantifier.
        /// </summary>
        internal static string RegExpInvalidQuantifier {
            get {
                return ResourceManager.GetString("RegExpInvalidQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid Unicode escape.
        /// </summary>
        internal static string RegExpInvalidUnicodeEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidUnicodeEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Lone quantifier brackets.
        /// </summary>
        internal static string RegExpLoneQuantifierBrackets {
            get {
                return ResourceManager.GetString("RegExpLoneQuantifierBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Nothing to repeat.
        /// </summary>
        internal static string RegExpNothingToRepeat {
            get {
                return ResourceManager.GetString("RegExpNothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: numbers out of order in {{}} quantifier.
        /// </summary>
        internal static string RegExpNumbersOutOfOrderInQuantifier {
            get {
                return ResourceManager.GetString("RegExpNumbersOutOfOrderInQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Range out of order in character class.
        /// </summary>
        internal static string RegExpRangeOutOfOrderInCharacterClass {
            get {
                return ResourceManager.GetString("RegExpRangeOutOfOrderInCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unmatched &apos;)&apos;.
        /// </summary>
        internal static string RegExpUnmatchedOpenParen {
            get {
                return ResourceManager.GetString("RegExpUnmatchedOpenParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unterminated character class.
        /// </summary>
        internal static string RegExpUnterminatedCharacterClass {
            get {
                return ResourceManager.GetString("RegExpUnterminatedCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unterminated group.
        /// </summary>
        internal static string RegExpUnterminatedGroup {
            get {
                return ResourceManager.GetString("RegExpUnterminatedGroup", resourceCulture);
            }
        }
    }
}
