//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acornima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyntaxErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyntaxErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acornima.Properties.SyntaxErrorMessages", typeof(SyntaxErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one underscore is allowed as numeric separator.
        /// </summary>
        internal static string ContinuousNumericSeparator {
            get {
                return ResourceManager.GetString("ContinuousNumericSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword must not contain escaped characters.
        /// </summary>
        internal static string InvalidEscapedReservedWord {
            get {
                return ResourceManager.GetString("InvalidEscapedReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hexadecimal escape sequence.
        /// </summary>
        internal static string InvalidHexEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidHexEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unexpected token.
        /// </summary>
        internal static string InvalidOrUnexpectedToken {
            get {
                return ResourceManager.GetString("InvalidOrUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression flags.
        /// </summary>
        internal static string InvalidRegExpFlags {
            get {
                return ResourceManager.GetString("InvalidRegExpFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Unicode escape sequence.
        /// </summary>
        internal static string InvalidUnicodeEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidUnicodeEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Duplicate capture group name.
        /// </summary>
        internal static string RegExpDuplicateCaptureGroupName {
            get {
                return ResourceManager.GetString("RegExpDuplicateCaptureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Incomplete quantifier.
        /// </summary>
        internal static string RegExpIncompleteQuantifier {
            get {
                return ResourceManager.GetString("RegExpIncompleteQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid capture group name.
        /// </summary>
        internal static string RegExpInvalidCaptureGroupName {
            get {
                return ResourceManager.GetString("RegExpInvalidCaptureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid character class.
        /// </summary>
        internal static string RegExpInvalidCharacterClass {
            get {
                return ResourceManager.GetString("RegExpInvalidCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid class escape.
        /// </summary>
        internal static string RegExpInvalidClassEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidClassEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid property name in character class.
        /// </summary>
        internal static string RegExpInvalidClassPropertyName {
            get {
                return ResourceManager.GetString("RegExpInvalidClassPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid decimal escape.
        /// </summary>
        internal static string RegExpInvalidDecimalEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidDecimalEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid escape.
        /// </summary>
        internal static string RegExpInvalidEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid group.
        /// </summary>
        internal static string RegExpInvalidGroup {
            get {
                return ResourceManager.GetString("RegExpInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid named capture referenced.
        /// </summary>
        internal static string RegExpInvalidNamedCaptureReference {
            get {
                return ResourceManager.GetString("RegExpInvalidNamedCaptureReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid named reference.
        /// </summary>
        internal static string RegExpInvalidNamedReference {
            get {
                return ResourceManager.GetString("RegExpInvalidNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid property name.
        /// </summary>
        internal static string RegExpInvalidPropertyName {
            get {
                return ResourceManager.GetString("RegExpInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid quantifier.
        /// </summary>
        internal static string RegExpInvalidQuantifier {
            get {
                return ResourceManager.GetString("RegExpInvalidQuantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Invalid Unicode escape.
        /// </summary>
        internal static string RegExpInvalidUnicodeEscape {
            get {
                return ResourceManager.GetString("RegExpInvalidUnicodeEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Lone quantifier brackets.
        /// </summary>
        internal static string RegExpLoneQuantifierBrackets {
            get {
                return ResourceManager.GetString("RegExpLoneQuantifierBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Nothing to repeat.
        /// </summary>
        internal static string RegExpNothingToRepeat {
            get {
                return ResourceManager.GetString("RegExpNothingToRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: numbers out of order in {{}} quantifier.
        /// </summary>
        internal static string RegExpRangeOutOfOrder {
            get {
                return ResourceManager.GetString("RegExpRangeOutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Range out of order in character class.
        /// </summary>
        internal static string RegExpRangeOutOfOrderCharacterClass {
            get {
                return ResourceManager.GetString("RegExpRangeOutOfOrderCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unmatched &apos;)&apos;.
        /// </summary>
        internal static string RegExpUnmatchedParen {
            get {
                return ResourceManager.GetString("RegExpUnmatchedParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unterminated character class.
        /// </summary>
        internal static string RegExpUnterminatedCharacterClass {
            get {
                return ResourceManager.GetString("RegExpUnterminatedCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: /{0}/{1}: Unterminated group.
        /// </summary>
        internal static string RegExpUnterminatedGroup {
            get {
                return ResourceManager.GetString("RegExpUnterminatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \8 and \9 are not allowed in strict mode.
        /// </summary>
        internal static string Strict8Or9Escape {
            get {
                return ResourceManager.GetString("Strict8Or9Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals with leading zeros are not allowed in strict mode.
        /// </summary>
        internal static string StrictDecimalWithLeadingZero {
            get {
                return ResourceManager.GetString("StrictDecimalWithLeadingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal escape sequences are not allowed in strict mode.
        /// </summary>
        internal static string StrictOctalEscape {
            get {
                return ResourceManager.GetString("StrictOctalEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal literals are not allowed in strict mode.
        /// </summary>
        internal static string StrictOctalLiteral {
            get {
                return ResourceManager.GetString("StrictOctalLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \8 and \9 are not allowed in template strings.
        /// </summary>
        internal static string Template8Or9Escape {
            get {
                return ResourceManager.GetString("Template8Or9Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal escape sequences are not allowed in template strings.
        /// </summary>
        internal static string TemplateOctalLiteral {
            get {
                return ResourceManager.GetString("TemplateOctalLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric separators are not allowed at the end of numeric literals.
        /// </summary>
        internal static string TrailingNumericSeparator {
            get {
                return ResourceManager.GetString("TrailingNumericSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Unicode code-point.
        /// </summary>
        internal static string UndefinedUnicodeCodePoint {
            get {
                return ResourceManager.GetString("UndefinedUnicodeCodePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input.
        /// </summary>
        internal static string UnexpectedEOS {
            get {
                return ResourceManager.GetString("UnexpectedEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected template string.
        /// </summary>
        internal static string UnexpectedTemplateString {
            get {
                return ResourceManager.GetString("UnexpectedTemplateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected identifier &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedTokenIdentifier {
            get {
                return ResourceManager.GetString("UnexpectedTokenIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected number.
        /// </summary>
        internal static string UnexpectedTokenNumber {
            get {
                return ResourceManager.GetString("UnexpectedTokenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected regular expression.
        /// </summary>
        internal static string UnexpectedTokenRegExp {
            get {
                return ResourceManager.GetString("UnexpectedTokenRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected string.
        /// </summary>
        internal static string UnexpectedTokenString {
            get {
                return ResourceManager.GetString("UnexpectedTokenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression: missing /.
        /// </summary>
        internal static string UnterminatedRegExp {
            get {
                return ResourceManager.GetString("UnterminatedRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing } in template expression.
        /// </summary>
        internal static string UnterminatedTemplateExpr {
            get {
                return ResourceManager.GetString("UnterminatedTemplateExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric separator can not be used after leading 0.
        /// </summary>
        internal static string ZeroDigitNumericSeparator {
            get {
                return ResourceManager.GetString("ZeroDigitNumericSeparator", resourceCulture);
            }
        }
    }
}
